import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import SEO from "../components/seo/SEO";
import "../blog/styles/case-study.css";

interface PostFrontmatter {
  slug?: string;
  title?: string;
  date?: string;
  excerpt?: string;
  description?: string;
  tags?: string[];
  readingTime?: string;
}

const modules = import.meta.glob<{ frontmatter?: PostFrontmatter }>(
  "../content/tech-news/*.mdx",
  { eager: true },
);

interface PostMeta {
  slug: string;
  title: string;
  date: string;
  deck: string;
  tags: string[];
  readingTime: string;
}

const formatDate = (iso: string): string => {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
};

const sorted = Object.entries(modules)
  .map(([path, mod]) => {
    const fileSlug = path.split("/").pop()?.replace(/\.mdx$/, "") ?? "";
    const fm = mod.frontmatter ?? {};
    return {
      _date: fm.date ?? "",
      slug: fm.slug ?? fileSlug,
      title: fm.title ?? fileSlug,
      date: fm.date ?? "",
      deck: fm.excerpt ?? fm.description ?? "",
      tags: fm.tags ?? [],
      readingTime: fm.readingTime ?? "",
    };
  })
  .sort((a, b) => (a._date < b._date ? 1 : -1));

const posts: PostMeta[] = sorted.map((p) => ({
  slug: p.slug,
  title: p.title,
  date: p.date,
  deck: p.deck,
  tags: p.tags,
  readingTime: p.readingTime,
}));

export default function TechNewsIndexPage() {
  return (
    <main className="cs">
      <SEO
        title="Tech News"
        description="Daily curated tech news for developers, auto-generated by AI."
        path="/tech-news"
      />

      <article className="cs-article">
        <Link to="/" className="cs-back">
          <ArrowLeft size={12} /> Kembali
        </Link>

        <p className="cs-eyebrow">
          <span>Tech News · AI Curated</span>
        </p>

        <h1 className="cs-title">Tech News</h1>

        <p className="cs-deck">
          Daily curated tech news for developers, automatically generated by AI
          from top sources like TechCrunch, The Verge, Hacker News, and more.
        </p>

        {posts.length === 0 ? (
          <p style={{ color: "var(--cs-ink-soft)" }}>
            Belum ada tech news. Cron job akan mulai generate konten harian.
          </p>
        ) : (
          <ul className="blog-list">
            {posts.map((post) => (
              <li key={post.slug} className="blog-row">
                <Link to={`/tech-news/${post.slug}`} className="blog-row__link">
                  <div className="blog-row__meta">
                    <span className="blog-row__date">
                      {formatDate(post.date)}
                      {post.readingTime ? ` · ${post.readingTime}` : ""}
                    </span>
                  </div>
                  <h2 className="blog-row__title">{post.title}</h2>
                  {post.deck && <p className="blog-row__deck">{post.deck}</p>}
                  {post.tags.length > 0 && (
                    <div className="blog-row__tags">
                      {post.tags.slice(0, 4).map((t) => (
                        <span key={t} className="blog-row__tag">
                          {t}
                        </span>
                      ))}
                    </div>
                  )}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </article>
    </main>
  );
}
